Repository vsquared-apps/go-weather, pull requests merged in 2020-10, with the labels that each got.

#1 documentation: update readme
  README.md
Labels: documentation

#2 Initialize Go module, add doc.go, add general layout
  cmd/.gitkeep
  doc.go
  go.mod
  internal/.gitkeep
  pkg/.gitkeep
Labels: documentation

#5 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#6 Create package for OpenWeatherMap API client
  go.mod
  go.sum
  pkg/.gitkeep
  pkg/openweather/current.go
  pkg/openweather/openweather-options.go
  pkg/openweather/openweather-options_test.go
  pkg/openweather/openweather.go
  pkg/openweather/openweather_test.go
Labels: enhancement, hacktoberfest-accepted

#7 Add options to get temperature in different units
  pkg/openweather/openweather-options.go
  pkg/openweather/openweather-options_test.go
  pkg/openweather/openweather.go
Labels: enhancement, hacktoberfest-accepted

#8 Create struct with city weather information
  pkg/openweather/current.go
Labels: enhancement, hacktoberfest-accepted

#9 Add test for (*CurrentService).ByCity method
  pkg/openweather/current_test.go
  pkg/openweather/testdata/current/location.json
Labels: hacktoberfest-accepted

#10 Create Makefile
  .gitignore
  Makefile
Labels: hacktoberfest-accepted

#11 Add readme and example for openweather package
  pkg/openweather/README.md
  pkg/openweather/example/main.go
Labels: hacktoberfest-accepted
